### ISSUE TITLE
Proposal: Split this project into 2 parts - jdbc-exporter and simple monitor

### ISSUE THREAD

**Issue by huksley** [zeebe-io/zeebe-simple-monitor#40]
Currently this project hosts both JDBC exporter (highly tied to H2 db) and web app simple monitor which uses this H2 db to show information about instances, workflows and upload new workflow.

Good idea is to create robust, tested JDBC exporter so other people can use it without bundled webapp, for example, hooking it up to https://github.com/metabase/metabase.

**Comment by saig0** [comment]
I'm not sure if it makes sense to extract the exporter because it is closely connected to the simple monitor. It is not designed as a generic JDBC exporter. Instead, it has a specific schema which contains the data that is needed by the monitor. 

However, if you think the schema is generic enough then feel free to create a new project for a JDBC exporter. I like the idea in general.
