### ISSUE TITLE
new payload is not been updated after resolving an incident

### ISSUE THREAD

**Issue by iury** [zeebe-io/zeebe-simple-monitor#55]
Hello,
I've created a dummy task that does nothing.
The first time I've created an instance with the payload { "test": 1 }
The task handler is coded to fail so I can see an incident.
After that I've clicked on resolve and put the payload { "test": 2 }
This time the task handler is coded to complete.
After refreshing the instance screen, the payload is completed but the payload is back to { "test": 1 }
I've put some logs and it seems the new payload on the resolve screen is never sent to the task handler.

**Comment by Zelldon** [comment]
Hey @iury ,

thanks for reporting this. 

It is a known bug in the broker and was fixed with https://github.com/zeebe-io/zeebe/pull/1672 ,
but it is not released yet. A new minor release is planned for next week, which will contain this fix.
We will try to update the simple-monitor as well after this release.

Greets,
Chris
